Stat svc
KurakinPavel/java-explore-with-me pull request #1
Opened 2024-06-18 15:02 UTC by KurakinPavel

2024-06-19 07:36 UTC, db-exp requested changes

2024-06-19 07:36 UTC, db-exp commented on stats-server/stats-server-dto/src/main/java/ru/practicum/statsserverdto/dto/HitDto.java
> +    @NotBlank
тогда можно и Size

2024-06-19 07:36 UTC, db-exp commented on stats-server/stats-server-service/src/main/java/ru/practicum/statsserverservice/HitController.java
> +    public List<StatsDtoOut> getHitStats(@RequestParam String start,
лучше добавить валидацию на start/end

2024-06-19 07:36 UTC, db-exp commented on stats-server/stats-server-service/src/main/java/ru/practicum/statsserverservice/model/Hit.java
> +    public Hit() {
NoArgsConstructor проще

2024-06-19 07:36 UTC, db-exp commented on stats-server/stats-server-service/src/main/java/ru/practicum/statsserverservice/model/Hit.java
> +    public Hit(int id, String app, String uri, String ip, LocalDateTime moment) {
AllArgsConstructor

2024-06-19 07:36 UTC, db-exp commented on stats-server/stats-server-client/src/main/resources/application.properties
> +stats-server.url=http://localhost:9090
лучше брать из docker-compose ${ИМЯ_ПЕРЕМЕННОЙ}

2024-06-19 11:04 UTC, KurakinPavel commented on stats-server/stats-server-dto/src/main/java/ru/practicum/statsserverdto/dto/HitDto.java
> +    @NotBlank
Исправлено.
По "timestamp" установлено ограничение @Size с учётом содержания ТЗ. 
По остальным полям ограничения @Size могут быть изменены с учётом дальнейшей разработки.

2024-06-19 11:05 UTC, KurakinPavel commented on stats-server/stats-server-service/src/main/java/ru/practicum/statsserverservice/HitController.java
> +    public List<StatsDtoOut> getHitStats(@RequestParam String start,
Валидация добавлена.

2024-06-19 11:05 UTC, KurakinPavel commented on stats-server/stats-server-service/src/main/java/ru/practicum/statsserverservice/model/Hit.java
> +    public Hit() {
Исправлено.

2024-06-19 11:06 UTC, KurakinPavel commented on stats-server/stats-server-service/src/main/java/ru/practicum/statsserverservice/model/Hit.java
> +    public Hit(int id, String app, String uri, String ip, LocalDateTime moment) {
Исправлено

2024-06-19 11:06 UTC, KurakinPavel commented on stats-server/stats-server-client/src/main/resources/application.properties
> +stats-server.url=http://localhost:9090
Исправлено.

2024-06-20 08:51 UTC, db-exp requested changes

2024-06-20 08:51 UTC, db-exp commented on stats-server/stats-server-service/src/main/java/ru/practicum/statsserverservice/HitController.java
> +    public List<StatsDtoOut> getHitStats(@RequestParam @NotBlank @Size(min = 19) String start,
тут лучше через DateTImeFormat https://www.baeldung.com/spring-date-parameters

2024-06-20 09:33 UTC, KurakinPavel commented on stats-server/stats-server-service/src/main/java/ru/practicum/statsserverservice/HitController.java
> +    public List<StatsDtoOut> getHitStats(@RequestParam @NotBlank @Size(min = 19) String start,
Исправлено.

2024-06-20 11:28 UTC, db-exp approved these changes

2024-06-20 12:20 UTC, merged